# Generated by Django 6.0.5 on 2026-05-25 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Solo se permiten letras y espacios.', regex='^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$')])),
                ('cardType', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMEX', 'American Express')], max_length=20)),
                ('cardNumber', models.CharField(max_length=16)),
                ('expirationDate', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator(message='Formato inválido. Use MM/YY', regex='^(0[1-9]|1[0-2])\\/([0-9]{2})$')])),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
    ]
